In [13]:
import numpy as np

In [14]:
is_right_oriented = True

# Initial Board

In [40]:
HEIGHT = 4
WIDTH = 4

In [16]:
board_ini = np.zeros((height,width))

board_ini[1:,0] = 1
board_ini[2,1] = 1

if not is_right_oriented:
    board_ini = np.flip(bload,1)


In [17]:
def is_outside(board, piece, pos):
    if pos[1] + piece.shape[1] > board.shape[1]\
        or pos[0] + piece.shape[0] > board.shape[0]: # bas
        return True
    return False

def can_put_bloc_at_pos(board, bloc, lig, col):
    if board[lig, col] == 1 and bloc == 1:
        return False
    return True

def can_insert(board, piece, pos):
    
    # Si la piece est en dehord du plateau on passe
    if is_outside(board, piece, pos):
        return False
    
    for i, horizontal in enumerate(piece):
        for j, bloc in enumerate(horizontal):
            if not can_put_bloc_at_pos(board, bloc, pos[0] + i, pos[1] + j):
                
                return False
    return True

def inserer_piece(board, piece, pos):

    if not can_insert(board, piece, pos):
        print("Insertion interdite")
        return -1

    ret = board.copy()
    for i, horizontal in enumerate(piece):
        for j, bloc in enumerate(horizontal):
            if bloc == 1:
                ret[pos[0] + i, pos[1] + j] = 1
    return np.array(ret)

In [18]:
def rot90(piece, nb_rot):
    if nb_rot == 0:
        return piece
    
    ret = np.zeros((piece.shape[1], piece.shape[0]))
    
    for i in range(piece.shape[1]):
        ret[i,:] = np.flip(piece[:,i])
    
    if nb_rot == 1:
        return ret
    else:
        return rot90(ret, nb_rot-1)
    return ret

def get_piece_orientations(piece):
    ret = []
    for i in range(4):
        ret.append(rot90(piece,i))
    return ret


# Pieces

In [19]:
o_piece = np.array([[1,1],[1,1]])
i_piece = np.array([[1,1,1,1]])
j_piece = np.array([[1,0,0],[1,1,1]])
l_piece = np.array([[0,0,1],[1,1,1]])
t_piece = np.array([[1,1,1],[0,1,0]])
s_piece = np.array([[0,1,1],[1,1,0]])
z_piece = np.array([[1,1,0],[0,1,1]])

# Get List Coup

In [20]:
# Pour chaque orientations
    # pour chaque possition
        # Si elle est possible
            # L'ajouter à la liste

In [61]:
#orientations = get_piece_orientations(piece)
#for oriente in orientations:
def get_piece_coups(board, piece):
    coups = []
    for x in range(HEIGHT):
        for y in range(WIDTH):
            if can_insert(board, piece, (x,y)):
                    coups.append([x,y])
    return coups

In [80]:
def clear_complete_lines(board):

    new_board = board.copy()

    for i,line in enumerate(board):
        if sum(line) == len(line):
            new_board = np.delete(new_board, i, 0)
            new_board = np.insert(new_board, 0, np.zeros(board.shape[1]), axis=0)

    return new_board



def jouer_piece(board, piece, pos, prev_coups):
    boards = []

    new_board = inserer_piece(board, piece, pos)
    new_board = clear_complete_lines(new_board)
    
    new_coup = prev_coups.copy()
    new_coup.append(pos)
    
    return (new_board, new_coup)

In [89]:

# Joue les pieces sur le board_ini et retourne les boards possible résultants
def jouer_pieces(board_ini, pieces):
    boards = [(board_ini, [])]
    while not len(pieces) == 0:
        piece = pieces.pop(0)
        new_boards = []
#         Pour chaques board à tester pour cette piece
        for board, prev_coups in boards:
            
            for coup in get_piece_coups(board, piece):
                
                board_pos = jouer_piece(board,piece, coup, prev_coups)
                
                new_boards.append(board_pos)
        
        boards = new_boards
    return boards
#     return np.unique(np.array(boards), axis=0)

In [ ]:
# Dis si un perfect clear est possible sur le board_ini avec les pieces
def perfect_is_possible(board_ini, pieces):
    boards = jouer_pieces(board_ini, pieces)
    board_vide = np.array([[0 for _ in range(WIDTH)] for _ in range(HEIGHT)])
    for board in boards:
        if np.array_equal(board_ini, board_vide):
            

In [81]:
jouer_piece(board_ini,  i_piece, (0,0), [])

(array([[0., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 0., 0., 0.]]), [(0, 0)])

In [90]:
pieces = [s_piece, z_piece, rot90(l_piece, 3)]
jouer_pieces(board_ini, pieces)

[(array([[0., 0., 0., 0.],
         [0., 1., 1., 1.],
         [1., 0., 0., 1.],
         [1., 1., 1., 0.]]), [[2, 1], [0, 0], [0, 2]]),
 (array([[0., 0., 0., 0.],
         [0., 0., 1., 1.],
         [1., 1., 0., 1.],
         [1., 1., 1., 0.]]), [[2, 1], [1, 0], [0, 2]]),
 (array([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), [[2, 1], [1, 0], [1, 2]])]

In [49]:
jouer_pieces(board_ini, [s_piece])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 1., 1., 0.]],

       [[0., 0., 1., 1.],
        [1., 1., 1., 0.],
        [1., 1., 0., 0.],
        [1., 0., 0., 0.]]])

In [ ]:
inserer_piece(board_ini, ro)

In [ ]:
# Récuperer la liste des pieces a venir
# Générer la liste des ordres de pieces possibles
# Pour chaque ordre possible
    # Récupérer les boards possible

In [ ]:
pieces = [s_piece, z_piece, rot90(l_piece, 3)]

for piece in pieces:
    

In [ ]:
def