In [1]:
import numpy as np

In [2]:
is_right_oriented = True

# Initial Board

In [3]:
height = 4
width = 4

In [157]:
board_ini = np.zeros((height,width))

board_ini[1:,0] = 1
board_ini[2,1] = 1

if not is_right_oriented:
    board_ini = np.flip(bload,1)


In [393]:
def is_outside(board, piece, pos):
    if pos[1] + piece.shape[1] > board.shape[1]\
        or pos[0] + piece.shape[0] > board.shape[0]: # bas
        return True
    return False

def can_put_bloc_at_pos(board, bloc, lig, col):
    if board[lig, col] == 1 and bloc == 1:
        return False
    return True

def can_insert(board, piece, pos):
    
    # Si la piece est en dehord du plateau on passe
    if is_outside(board, piece, pos):
        return False
    
    for i, horizontal in enumerate(piece):
        for j, bloc in enumerate(horizontal):
            if not can_put_bloc_at_pos(board, bloc, pos[0] + i, pos[1] + j):
                
                return False
    return True

def inserer_piece(board, piece, pos):

    if not can_insert(board, piece, pos):
        print("Insertion interdite")
        return -1

    ret = board.copy()
    for i, horizontal in enumerate(piece):
        for j, bloc in enumerate(horizontal):
            if bloc == 1:
                ret[pos[0] + i, pos[1] + j] = 1
    return np.array(ret)

In [375]:
can_put_bloc_at_pos(board, 1, 3,0)

False

In [380]:
inserer_piece(board_ini, rot90(t_piece,2), (2,1))

1 2
2 2
3 2
1 3
2 3
3 3


array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 2., 0.],
       [1., 2., 2., 2.]])

In [314]:
board_ini

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [88]:
def rot90(piece, nb_rot):
    if nb_rot == 0:
        return piece
    
    ret = np.zeros((piece.shape[1], piece.shape[0]))
    
    for i in range(piece.shape[1]):
        ret[i,:] = np.flip(piece[:,i])
    
    if nb_rot == 1:
        return ret
    else:
        return rot90(ret, nb_rot-1)
    return ret

In [98]:
def get_piece_orientations(piece):
    ret = []
    for i in range(4):
        ret.append(rot90(piece,i))
    return ret


# Pieces

In [294]:
o_piece = np.array([[1,1],[1,1]])
i_piece = np.array([[1,1,1,1]])
j_piece = np.array([[1,0,0],[1,1,1]])
l_piece = np.array([0,0,1],[1,1,1])
t_piece = np.array([[1,1,1],[0,1,0]])
s_piece = np.array([[0,1,1],[1,1,0]])
z_piece = np.array([[1,1,0],[0,1,1]])
s_piece = 

# Get List Coup

In [124]:
# Pour chaque orientations
    # pour chaque possition
        # Si elle est possible
            # L'ajouter à la liste

In [133]:
#orientations = get_piece_orientations(piece)
#for oriente in orientations:
def get_piece_coups(board, piece):
    coups = []
    for x in range(height):
        for y in range(width):
            if can_insert(board, piece, (x,y)):
                    coups.append((x,y))
    return coups

In [139]:
# Récupérer les boards pour chanque orientations d'une piece
def jouer_piece(board, piece):
    boards = []
    orientations = get_piece_orientations(piece)
    for oriente in orientations:
        coups = get_piece_coups(board, oriente)

        for coup in coups:
            boards.append(inserer_piece(board, oriente, coup))
    
    return boards

In [389]:
# Joue les pieces sur le board_ini et retourne les boards possible résultants
def jouer_pieces(board_ini, pieces):
    boards = [board_ini]
    while not len(pieces) == 0:
        piece = pieces.pop(0)
        new_boards = []
        for board in boards:
            new_boards.extend(jouer_piece(board,piece))
        boards = new_boards
        
    return np.unique(np.array(boards), axis=0)

In [397]:
pieces = [t_piece, j_piece, i_piece]
boards = jouer_pieces(board_ini, pieces)

In [398]:
boards

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [396]:
len(boards)

12

In [306]:
rot90(t_piece,2)

array([[0., 1., 0.],
       [1., 1., 1.]])